#!/bin/sh

case $BLOCK_BUTTON in
    3) "$TERMINAL" -e "$EDITOR" "$0";;
esac

for battery in /sys/class/power_supply/BAT?
do
    capacity=$(cat "$battery"/capacity) || break
    status=$(sed "s/[Dd]ischarging//;s/[Nn]ot charging/ /;s/[Cc]harging//;s/[Uu]nknown//;s/[Ff]ull//" "$battery"/status)

     [ "$capacity" -le 25 ] && [ "$status" = "" ] && status=""

    echo "$status  $capacity"
done

# vim: set syntax=shell
