#!/bin/sh

case $BLOCK_BUTTON in
    2) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

usage=$(mpstat | awk -F " " '/all/ {print 100 - $13"%"}')
temp=$(sensors 2> /dev/null | awk '/Core 0/ {print $3}')
temp=${temp#+}

echo "$usage ($temp)"

# vim: set syntax=shell
