#!/bin/sh

filter() { mpc | sed "/^volume:/d;s/\\&/&amp;/g;s/\\[paused\\].*/⏸/g;/\\[playing\\].*/d" | paste -sd '';}

case $BLOCK_BUTTON in
	1) mpc toggle | filter ;;  # left click, pause/unpause
    2) "$TERMINAL" -e "$EDITOR" "$0" ;;
	4) mpc prev   | filter ;;  # scroll up, previous
	5) mpc next   | filter ;;  # scroll down, next
esac

pidof -x mpdup >/dev/null 2>&1 || mpdup >/dev/null 2>&1 &

# vim: set syntax=shell
