#!/bin/sh

case $BLOCK_BUTTON in
	1) pamixer -t ;;
	2) "$TERMINAL" -e "$EDITOR" "$0" ;;
	3) setsid -f "$TERMINAL" -e pulsemixer ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
esac

volstat="$(pactl list sinks)"
echo "$volstat" | grep -q "Mute: yes" && printf "MUT\\n" && exit
vol="$(echo "$volstat" | grep '[0-9]\+%' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"

if [ "$vol" -gt "70" ]; then
	icon="VOL"
elif [ "$vol" -lt "30" ]; then
	icon="vol"
else
	icon="Vol"
fi

printf "%s %s\\n" "$icon" "$vol"

# vim: set syntax=shell
