#!/bin/sh

case $BLOCK_BUTTON in
	1) pamixer -t ;;
	2) "$TERMINAL" -e "$EDITOR" "$0" ;;
	3) setsid -f "$TERMINAL" -e pulsemixer ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
esac

[ "$(pulsemixer --get-mute)" == 1 ] && printf "\\n" && exit
vol="$(pulsemixer --get-volume)"
vol="${vol%% *}"

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -lt "30" ]; then
	icon=""
else
	icon=""
fi

printf "%s %s\\n" "$icon" "$vol"

# vim: set syntax=shell
