#!/usr/bin/env bash
readonly ID_PREVIEW="preview"

[ -e "$FIFO_UEBERZUG" ] || exit 1

if [[ "$1" == "draw" ]]; then
    declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
        [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
        [path]="${PWD}/$6") \
    > "$FIFO_UEBERZUG"

elif [[ "$1" == "pdfpreview" ]]; then
    echo -e "Loading preview..\nFile: $6"
    [[ ! -d "/tmp${PWD}/$6/" ]] && mkdir -p "/tmp${PWD}/$6/"
    [[ ! -f "/tmp${PWD}/$6.png" ]] && pdftoppm -png -singlefile "$6" "/tmp${PWD}/$6"
    declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
        [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
        [path]="/tmp${PWD}/$6.png") \
    > "$FIFO_UEBERZUG"

else
    declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") \
    > "$FIFO_UEBERZUG"
fi
