#!/bin/sh
while read file
do
        case "$1" in
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "R")
            convert -rotate -90 "$file" "$file" ;;
        "y")
            echo -n "$file" | xclip -selection clipboard &&
            notify-send "$file copied to clipboard" & ;;
        "Y")
		    readlink -f "$file" | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
        "d")
            [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] \
                && rm "$file" && notify-send "$file deleted." ;;
        "w")
            xwallpaper --zoom $file;;
        "g")
            pacman -Q gimp 2>/dev/null && gimp "$file" & ;;
        esac
done

# vim: set syntax=shell
