#!/bin/sh

dt=10
unit="Mibs"
conv=$((dt * 1024 * 1024 / 8))

#iface="wlp6s0"
iface="enp7s0"

case "$BLOCK_BUTTON" in
  1) nm-connection-editor
esac


#BEGIN{old_received=0; old_sent=0}
(while true; do cat /proc/net/dev; sleep "$dt"; done) |\
  stdbuf -oL grep "^[ ]*$iface:" |\
  awk -v conv=$conv -v unit=$unit -v iface=$iface '
  BEGIN{
    orr=0
    os=0}
  {
    nr=$2
    ns=$10
    r=(nr-orr)/conv
    s=(ns-os)/conv
    if(orr >0 && os >0){
      printf "%5.2f%s/%5.2f%s \n", r, unit, s, unit,
      fflush(stdout)
    }
    orr=nr
    os=ns
  }'

