#!/bin/sh

total=$(awk '/MemTotal:/ {print $2}' /proc/meminfo)
available=$(awk '/MemAvailable:/ {print $2}' /proc/meminfo)
usage="$((($total-$available)/1024))"
total=$(($total/1024))
echo "$usage""MB/$total""MB"
