#!/bin/sh

# xinitrc runs at when startx executes

# executes xprofile to start some daemon programs
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/xprofile" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/xprofile"

# start window manager
#bspwm

 sxhkd -c ~/.config/sxhkd/dwm_sxhkdrc &
 flameshot config --filename "screenshot_%F%T" --trayicon false --maincolor #ffffff --contrastcolor #48a8da
 flameshot &
 dwm

