#!/bin/sh

# xinitrc runs at when startx executes

# executes xprofile to start some daemon programs
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/xprofile" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/xprofile"

picom -CG &
$HOME/.config/polybar/./launch.sh

# start window manager
bspwm

