#!/bin/sh

mpd ~/.config/mpd/mpd.conf &
dunst &
sxhkd -c ~/.config/sxhkd/dwm_sxhkdrc &
picom --config $HOME/.config/picom/picom.conf &
xsetroot -cursor_name left_ptr &
flameshot config --filename "screenshot_%F%T" --trayicon false --maincolor #ffffff --contrastcolor #48a8da
flameshot &

~/.screenlayout/./dual_monitor.sh
