#!/usr/bin/bash

if [ -z $1 ]; then
    echo "Usage: $0 <Class of the window>"
    exit 1
fi

pids=$(xdotool search --class ${1})

for pid in $pids; do
    echo "Toggle $pid"
    bspc node $pid --flag hidden -f
done

#if [ ${#pids[@]} -eq 0]; then
#    start_application($1)
#fi
